import matplotlib.pyplot as plt                                                                                                                                                                                                           
import pandas as pd                                                                                                                                                                                                                       
import numpy as np                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
# Generate sample data (replace with actual data if available)                                                                                                                                                                            
time = pd.date_range('2026-03-05 09:00:00', '2026-03-05 13:00:00', freq='min')                                                                                                                                                            
page_views = np.concatenate([np.zeros(60), np.random.randint(3, 8, size=42), np.zeros(60)]) # Simulate spike                                                                                                                                                                                                                                                                                                                                                                       
# Create the plot                                                                                                                                                                                                                         
plt.figure(figsize=(12, 6))                                                                                                                                                                                                               
plt.plot(time, page_views, marker='o', linestyle='-', color='blue')                                                                                                                                                                       
plt.title('Page Views - MSI MAG B850 Tomahawk Max WiFi Motherboard')                                                                                                                                                                      
plt.xlabel('Time')                                                                                                                                                                                                                        
plt.ylabel('Number of Page Views')                                                                                                                                                                                                        
plt.grid(True)                                                                                                                                                                                                                            
plt.tight_layout()                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            
# Save the chart as a PNG file (Replace 'chart.png' with desired filename)                                                                                                                                                                
plt.savefig('chart.png')                                                                                                                                                                                                                  
plt.show()